### ISSUE TITLE
Unhandled Exception: System.ArgumentNullException: Value cannot be null. Parameter name: stream

### ISSUE THREAD

**Issue by Andree12** [Romulion/GameEngine#1]
```
Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: stream
   at System.IO.StreamReader..ctor(Stream stream, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean leaveOpen)
   at System.IO.StreamReader..ctor(Stream stream)
   at Toys.ShaderManager.ReadFromAssetStream(String path) in C:\GameEngine-master\GameEngine-master\Toys\Engine\Objects\ShaderManager.cs:line 98
   at Toys.ShaderManager.LoadShader(String name) in C:\GameEngine-master\GameEngine-master\Toys\Engine\Objects\ShaderManager.cs:line 43
   at Toys.DynamicFormScript.Awake() in C:\GameEngine-master\GameEngine-master\Toys\Engine\Modules\DinamicForm\DynamicFormScript.cs:line 53
   at Toys.ScriptingEngine.Awake() in C:\GameEngine-master\GameEngine-master\Toys\Engine\Systen\ScriptingEngine.cs:line 43
   at Toys.CoreEngine.Update(Object sender, FrameEventArgs e) in C:\GameEngine-master\GameEngine-master\Toys\Engine\CoreEngine.cs:line 81
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.OnUpdateFrame(FrameEventArgs e) in I:\work\github\opentk\src\OpenTK\GameWindow.cs:line 868
   at OpenTK.GameWindow.RaiseUpdateFrame(Stopwatch watch, Double elapsed, Double& timestamp) in I:\work\github\opentk\src\OpenTK\GameWindow.cs:line 460
   at OpenTK.GameWindow.DispatchUpdateFrame(Stopwatch watch) in I:\work\github\opentk\src\OpenTK\GameWindow.cs:line 417
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in I:\work\github\opentk\src\OpenTK\GameWindow.cs:line 373
   at Toys.MainProcess.Main(String[] args) in C:\GameEngine-master\GameEngine-master\Toys\MainProcess.cs:line 59
```

I have a error with this while I'm trying to open a .lmd file with the compiled .exe, did I do something wrong or it is a bug?

**Comment by Romulion** [comment]
It was bug.
Forgot to include shader in git.
